### ISSUE TITLE
Server-side routing and rendering

### ISSUE THREAD

**Issue by timbrandin** [meteor/react-packages#15] opened 2015-06-18 17:14 UTC
Just a thought. ;)

**Comment by grigio** [comment] 2015-06-18 17:24
+1

**Comment by AdamBrodzinski** [comment] 2015-06-18 23:24
I'm working on React serverside currently, hopefully i'll have a spiked branch ready this weekend for an open source Meteor/React app i'm working on: https://github.com/AdamBrodzinski/react-ive-meteor . I can post back here if it's helpful. 

The concept would be that the first request is rendered on the server and flushed to the client and then once parsed, the clientside router would take over as usual.

**Comment by grigio** [comment] 2015-06-19 08:08
I agree the steps, React can render to string,.. but I'd like to see how to deal with Collections. `Posts.find({})` returns all the data on the server and only the data filled by the subscription on the client.
The subscription isn't available in the server, so there is the risk to render different data in the server and on the client and probably, another limitation would that it only work for non-authenticated pages, because the authentication in Meteor is over DDP. What do you think?

**Comment by AdamBrodzinski** [comment] 2015-06-19 15:13
@grigio  Yes I agree, that's the tough part! Although having an HTML skeleton while data is being fetching the normal way would be a big step forward.

Keep in mind these thoughts are just spinning around my head and I haven't had a chance to really work them out. I don't see how to get a seamless integration without full core integration with some kind of serverside minimono and subscriptions. However here are some hacks i've been thinking of.

Getting past fetching the entire db with `Posts.find()` is troublesome. A work around would be to stub them before rendering and restore them after the html is made. However if you get your data from `this.props.posts` instead, it makes it much less of an issue.

The best thing I can think of is using a `PostsContainer` component wrapper. These containers are just basically fetching data that `PostsList` and passing them into the `PostsLists` view via props. It can have `if meteor.isServer/Client` blocks to determine what gets fetched on the server. You could even have separate client/server container files if needed. Facebook uses this concept of data fetching containers so that the teams can re-use components easier.

Another idea is to fetch the data on the sever and save to a global variable. The client could check if this exists and if it doesn't *and is client*, then use `Posts.find`. However something like Fast-Render could prob. do this more transparently?

I don't know how to securely get around first page load for authenticated pages. I think the best bet here is to render everything else and fill in the missing bits once logged in. Facebook does something similar on their newsfeed where the posts have a width/height and a graphic background that fills the space until the content is rendered in.

I've been thinking about how to integrate this serverside fetching seamlessly using a [Meteor Relay](https://forums.meteor.com/t/react-meteor-open-source-feed-example-app/5611/4) abstraction for data fetching... by having this facade for fetching it could make it easier to return data on the serverside.

At any rate i'd love to hear other ideas!

**Comment by stubailo** [comment] 2015-06-26 22:17
@AdamBrodzinski "Although having an HTML skeleton while data is being fetching the normal way would be a big step forward."

I'm currently working on a `static-html` package that will let you serve custom HTML without using the `templating` package, and without Blaze.

**Comment by AdamBrodzinski** [comment] 2015-06-27 01:19
@stubailo Nice! You guys are killing it! :+1:

**Comment by stubailo** [comment] 2015-06-27 02:28
@AdamBrodzinski yeah, I think my favorite part of this project is that so far most stuff has not involved changes to actual Meteor. Packages are pretty powerful!

However, bigger changes might be incoming soon, things are going to get really exciting around here.

**Comment by AdamBrodzinski** [comment] 2015-06-27 15:49
@stubailo *"However, bigger changes might be incoming soon, things are going to get really exciting around here"*

This is really exciting :smiley: I've been kind of bummed on how Meteor is falling behind the norm in certain areas with the recent trend in ES6/7, webpack, ES6 Modules, serverside rendering, etc...  Can't wait to see what's next!

**Comment by pronevich** [comment] 2015-06-27 16:25
I agree with that. So many tools build with webpack, feels like a standard of React ecosystem.

**Comment by grigio** [comment] 2015-06-27 17:57
I agree componentize all things :) ReactJS and it's ecosystem is very interesting, it works on the web of today but it is beyond the web (DOM) itself and Meteor has still a place in the data synchronization stack.

**Comment by buduguru** [comment] 2015-06-28 17:00
waiting for SSR too

**Comment by jbbr** [comment] 2015-06-28 20:37
+1

**Comment by AdamBrodzinski** [comment] 2015-06-29 15:05
I have a spike repo to use React-Router for server-side rendering. However there is an issue with using it on the server. It's throwing an undefined `toUpperCase` which I think is from missing `module.exports`? 

https://github.com/AdamBrodzinski/meteor-react-ssr-spike

Happy to accept PR's :smiley: I might branch off a FlowRouter branch to get going.... not sure how much tinkering it will take to get React-Router to work with Meteor serverside.

**Comment by timbrandin** [comment] 2015-06-29 16:26
This is just what I asked for @AdamBrodzinski !! But I wish it used FlowRouter as it would get much easier to integrate both say logged in parts that use a hefty load of already existing template supporting packages, and React to build awesome static pages that load instantly on a page request ... a great combo I hope :+1: :)

**Comment by timbrandin** [comment] 2015-06-29 16:27
@stubailo I curious what a static-html package would do! I hope it renders templates :8ball:

**Comment by engelgabriel** [comment] 2015-06-29 21:14
:+1:

**Comment by stubailo** [comment] 2015-06-29 21:18
Please do not post comments such as :+1: or "+1" - it doesn't contribute to the discussion. The number of comments on this issue won't help indicate its importance relative to the number of people using these packages.

It would be much more helpful to have comments describing your use cases for server side rendering, what an implementation would look like, articles about usefulness of server side rendering, etc.

**Comment by timbrandin** [comment] 2015-06-30 01:33
Hey @stubailo, hwo does [this example](https://github.com/timbrandin/meteor-iosmorphic-react-templating) contribute?

I repurposed your JSX build plugin to create templates ala Blaze in React, do you like it? I certainly do!
Say Hello to: [timbrandin:jsx-templates](https://atmospherejs.com/timbrandin/jsx-templating)
```js
meteor add timbrandin:jsx-templates
```

This is what I requested, though it would be nice if the package RouteCore I'm using could be simplified internally and use your react-packages instead.

Have a great evening guys!

**Comment by stubailo** [comment] 2015-06-30 01:58
Hi @timbrandin! Sorry if I was a little too harsh in that comment, just sometimes it becomes hard to see the actual content amid :+1:s.

That package looks _**AWESOME**_. I love the idea to make it easy to use React under the hood but still have templates. There was actually just a post about this in the forums: https://forums.meteor.com/t/preview-of-official-react-support/6150/31?u=sashko

Going to start a new thread about this, can't wait to see your package get completed: https://github.com/meteor/react-packages/issues/32

I think RouteCore has the right idea about moving away from global variables, since those globals don't work very well on the server. Hopefully they can update to use our `react-runtime` package so that everyone can be based off of the same thing.

**Comment by stubailo** [comment] 2015-06-30 02:19
Also, @timbrandin the JSX package wasn't me, it was @dgreensp :]

**Comment by timbrandin** [comment] 2015-06-30 06:45
Oh, no worries, I'm just an ass making fun of such things ;) I'm sorry!

RouteCore should definitely be based of ```react-runtime```, I hope @mystor sees this discussion.

Great that you like it, I hope it's not to hard implementing events which seems as the biggest task ahead. Need to learn how Meteor does this, if it's using jquery or just [sizzle](http://sizzlejs.com/).

Oh, I have to change that credit in the README. :+1: Anyway, how about adding this jsx-templating into this suite of packages instead? I could do a PR for it if you want to!

**Comment by stubailo** [comment] 2015-06-30 16:35
@timbrandin I think this repository is for packages maintained by MDG directly, so that we can provide proper support. We aren't done with the original planned work yet, so I don't think it's a good idea at this point to add an extra thing that we have to maintain. And at the end of the day, there really isn't a big technical difference between a package in this repo and one outside it.

IMO this is an ideal case for a community tie-in package, so that people can look at different templating models and decide which one works for them. If it turns out really well and we are done with the initial version of the pure React integration, we can add things like templating, CJSX, typed JSX, etc.

**Comment by timbrandin** [comment] 2015-07-01 15:08
Alright, in that regard, its better for now to go community supported package.

**Comment by mystor** [comment] 2015-07-01 15:09
@timbrandin I don't really have time to move routecore over to using react-runtime, but if someone wants to do it for me, I can give them commit access.

**Comment by timbrandin** [comment] 2015-07-01 15:27
No need for commit access, I'd prefer you reviewed any PRs coming in first.
// T

2015-07-01 17:09 GMT+02:00 Michael Layzell <notifications@github.com>:

> @timbrandin <https://github.com/timbrandin> I don't really have time to
> move routecore over to using react-runtime, but if someone wants to do it
> for me, I can give them commit access.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/15#issuecomment-117711045>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by arunoda** [comment] 2015-07-01 16:05
Guys, I just started playing with SSR and React and I could be able to build a proper SSR support with data management as well. (using existing subscriptions)

So, users can write just the way they do normally. FlowRouter will do the hard work.

* See demo: http://flow-react-ssr.meteor.com/
* See my detailed post: [Meteor SSR Support with FlowRouter and React](https://kadira.io/blog/meteor-ssr-support-using-flow-router-and-react/)

**Comment by grigio** [comment] 2015-07-01 17:01
@arunoda this is great! Why do you say this isn't ready for production? Mostly of the functions called seems pretty known on meteor and react side.
A side effect i see is the bigger initial request size, but i shouldnt be a problem if you publish a few data per page

**Comment by arunoda** [comment] 2015-07-01 17:07
We need to do more on handling subscriptions on the server side. This is basic implementation. For an example, currently if there is a custom publication this does not work well. Login support is also not there.

But, that's fine. We've already solved those issues with FastRender and we simply need to find a way to bridge it.

Currently we need to send data as well to the client. That's required by react. But, it seems unnecessary. I'm thinking of ways to avoid it too.

**Comment by mystor** [comment] 2015-07-01 17:09
In routecore, I used fastrender for everything, but didn't handle
collections on the server the same as on the client (I didn't restrict to
published data on server). I'm assuming that's what you're working on?

**Comment by arunoda** [comment] 2015-07-01 17:14
@mystor yeah. This solution has a isolate environment for each routes and they've their own set of collections. Those collections will get filled with the data from subscriptions.

With that, users don't need to write code specific for SSR.

**Comment by mystor** [comment] 2015-07-01 17:21
Makes sense, I could probably do the same thing with contexts in routecore.
Your solution is probably more polished though :).

**Comment by arunoda** [comment] 2015-07-01 17:22
Ha ha.  Thanks.
May be I can isolate some stuff. Who know you can use them too.

**Comment by AdamBrodzinski** [comment] 2015-07-01 17:58
@arunoda Wow this is great! Will you be able to subscribe in the component or does the subscription have to happen in the router for SSR? I've found it easier to reason about if the the components subscribe to the data they need instead of having it all jammed into the router (especially if it uses state that's not in the url).

Keep up the good work!

**Comment by timbrandin** [comment] 2015-07-01 18:03
WOW! Amazing! I can't wait for FlowRouter to get this, I was actually
trying to use FlowRouter at first, but realized it doesn't do server side,
great work @arunoda!

2015-07-01 19:58 GMT+02:00 Adam Brodzinski <notifications@github.com>:

> @arunoda <https://github.com/arunoda> Wow this is great! Will you be able
> to subscribe in the component or does the subscription have to happen in
> the router for SSR? I've found it easier to reason about if the the
> components subscribe to the data they need instead of having it all jammed
> into the router (especially if it uses state that's not in the url).
>
> Keep up the good work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/15#issuecomment-117768898>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by arunoda** [comment] 2015-07-01 18:11
@AdamBrodzinski you can use subscriptions inside components as well. No issues on that. 

@timbrandin server side rendering is planned for version 3. We are going to release 2.0 next week for sure. Then, we can officially start on 3.0 and SSR.

I'll be also develop in fashion where you can start use right away, without waiting to the end to get the 3.0

**Comment by stubailo** [comment] 2015-07-01 18:13
Really awesome discussion. @arunoda will this always be built into the router? Would it be possible to split out the server-side rendering component/subscription isolation so that it could be used with other routers (specifically React Router and other React-specific libraries)

**Comment by arunoda** [comment] 2015-07-01 18:16
I think that can be done. But the problem is there should be a server side routing part. So, basically we can move out subscription isolations into a separate package. Still, someone has to glue it for react-router.

**Comment by stubailo** [comment] 2015-07-01 18:21
I'll give it a try in the next few weeks if I have time.

**Comment by timbrandin** [comment] 2015-07-01 20:36
Just playing around with your code @arunoda, I like it a lot!
https://github.com/timbrandin/hello-react-meteor

2015-07-01 20:21 GMT+02:00 Sashko Stubailo <notifications@github.com>:

> I'll give it a try in the next few weeks if I have time.
>
> On Wed, Jul 1, 2015 at 11:16 AM Arunoda Susiripala <
> notifications@github.com>
> wrote:
>
>
> > I think that can be done. But the problem is there should be a server
> side
> > routing part. So, basically we can move out subscription isolations into
> a
> > separate package. Still, someone has to glue it for react-router.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/meteor/react-packages/issues/15#issuecomment-117779453>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/15#issuecomment-117782690>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by arunoda** [comment] 2015-07-01 23:55
That's nice to see :)

**Comment by timbrandin** [comment] 2015-07-02 00:47
Oh @arunoda btw, I also tested it out on SpaceTalk's homepage! http://spacetalkapp.com/

Its performing amazingly well out of the box, I'm super thrilled atm.
If you want to check the out code, it's over here: https://github.com/SpaceTalk/SpaceTalk-Homepage/tree/react

**Comment by arunoda** [comment] 2015-07-02 00:49
Yeah! I got the notification from Slack. I saw the count of the Slack
widget still comes with a delay. Does it get data via a subscription ?

**Comment by timbrandin** [comment] 2015-07-02 06:23
Yeah you're right, it doesn't capture the subscription on the server. I wonder why.. 

Skickat från min iPhone

> 2 jul 2015 kl. 02:49 skrev Arunoda Susiripala <notifications@github.com>:
> 
> Yeah! I got the notification from Slack. I saw the count of the Slack
> widget still comes with a delay. Does it get data via a subscription ?
>

**Comment by arunoda** [comment] 2015-07-02 06:26
You need to do the subscription for that, inside the React component. May
be in getMeteorData or getInitialState

**Comment by timbrandin** [comment] 2015-07-02 15:36
@arunoda I could not get that to work though, I put my subs in the router instead.

**Comment by arunoda** [comment] 2015-07-02 15:57
May be I need to look at more.

**Comment by giantelk** [comment] 2015-07-11 17:42
Is this a suitable short term hack around: Use Iron-Router, render React components into Iron-Router so can use Meteor `spiderable` package for SEO?

**Comment by timbrandin** [comment] 2015-07-11 21:27
No it is not. Blaze templates does not load on the server.

**Comment by buduguru** [comment] 2015-07-12 10:28
@arunoda @timbrandin well done! thanks

**Comment by buduguru** [comment] 2015-07-12 10:31
@timbrandin BTW the buttons (to github and trello) are non-clickable on http://spacetalkapp.com/ (maybe just for me)

**Comment by arunoda** [comment] 2015-07-13 22:24
Update on SSR:

I re-built our kadira.io web app via React. So, basically I wanted SSR. It seems like I implemented it which can be mentioned to be an alpha stage produce and we can see a release soon.

React takes a lot of CPU resources on the server. See: https://twitter.com/kadirahq/status/620467416749838336

So, I followed some basic caching and solved this issue. Actually, that cache will get invalidated when users get the data via the normal collections. Then it's kind a smart cache. This is great for public pages and save the CPU.

For non-public pages, I am not quite sure enabling SSR is a good idea at this stage, since it eats CPU. Let's see what we can do about it.

**Comment by timbrandin** [comment] 2015-07-13 23:26
I've also noticed high CPU on React rendered pages, I'd love to see a
solution with caching turned on @arunoda!

2015-07-14 0:24 GMT+02:00 Arunoda Susiripala <notifications@github.com>:

> Update on SSR:
>
> I re-built our kadira.io web app via React. So, basically I wanted SSR.
> It seems like I implemented it which can be mentioned to be an alpha stage
> produce and we can see a release soon.
>
> React takes a lot of CPU resources on the server. See:
> https://twitter.com/kadirahq/status/620467416749838336
>
> So, I followed some basic caching and solved this issue. Actually, that
> cache will get invalidated when users get the data via the normal
> collections. Then it's kind a smart cache. This is great for public pages
> and save the CPU.
>
> For non-public pages, I am not quite sure enabling SSR is a good idea at
> this stage, since it eats CPU. Let's see what we can do about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/15#issuecomment-121079348>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by johanholmerin** [comment] 2015-07-18 18:23
I compared how long it takes for the page to be visually complete with and without SSR, using meteorhacks:flow-router-ssr. SSR is an improvement, but Meteors way of putting all your Javascript and CSS as blocking resources in `head` limits the effect. For a more info take a look at [johanholmerin/meteor-ssr-performance](https://github.com/johanholmerin/meteor-ssr-performance).

**Comment by arunoda** [comment] 2015-07-19 02:39
You are correct. This SSR is for bots. Not for hamans. For humans it comes
at a very cost with high CPU usage with no result in page loading
improvement. May be worst.

So, I am thinking a way to do it what google inbox does. Render the HTML.
Freeze all events while js and other stuff properly gets loaded.

**Comment by timbrandin** [comment] 2015-07-20 10:59
@johanholmerin could you possibly publish your changes that places meteor's head resources in the footer? Great work btw, would like to try it on my three React sites with a speed test as you've done.

**Comment by arunoda** [comment] 2015-07-20 11:18
@johanholmerin would you like to send me a PR for the ssr branch. I like the use the `cheerio` as well. For this improvement (moving scripts and css to the bottom), I'd like to make it optional. (ask some option from the user)

**Comment by johanholmerin** [comment] 2015-07-20 20:28
[PR submitted](https://github.com/meteorhacks/flow-router/pull/217)

**Comment by jedwards1211** [comment] 2015-07-21 17:06
As others have alluded to, I think using Webpack for the frontent will always be your best bet.

**Comment by stubailo** [comment] 2015-07-21 17:07
What does using webpack have to do with SSR?

**Comment by jedwards1211** [comment] 2015-07-21 21:20
@stubailo Nothing in particular, I was just responding to some other comments about Webpack in this thread.

**Comment by filipenevola** [comment] 2021-01-21 10:41
I'm closing this just because it's too old. We can open new issues for items that are still valid.

**Closed by filipenevola** 2021-01-21 10:41 UTC
Labels: community-package-encouraged, discussion
