### ISSUE TITLE
Allow separation of templates from React

### ISSUE THREAD

**Issue by mitar** [meteor/react-packages#36] opened 2015-07-02 19:19 UTC
Is it possible to somehow still have separated templates and React rendering? I like clean separation of concerns.

Something like [react-separate-template](https://github.com/redexp/react-separate-template), but just if it would be spacebars. :-)

**Comment by stubailo** [comment] 2015-07-02 21:38
Duplicate of https://github.com/meteor/react-packages/issues/32, I think!

**Closed by stubailo** 2015-07-02 21:38 UTC
