### ISSUE TITLE
Get warning about deprecated react lifecycle methods

### ISSUE THREAD

**Issue by zhaoyao91** [meteor/react-packages#275] opened 2019-09-23 00:44 UTC
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReactMeteorDataComponent

**Comment by StorytellerCZ** [comment] 2019-09-23 01:35
Duplicate of #256 
Solutions are already suggested in PRs.

**Closed** 2019-09-23 06:44 UTC
