### ISSUE TITLE
Semantic UI Infinite scroller 'visibility' bug with Meteor & React-Packages and Chrome desktop browser.

### ISSUE THREAD

**Issue by giantelk** [meteor/react-packages#84] opened 2015-08-09 20:43 UTC
**Semantic UI Infinite scroller 'visibility' bug with Meteor & React-Packages and Chrome desktop browser.**

Bug description is below and a repo here:
https://github.com/giantelk/react-meteor-infinite-scroll-semantic-ui
- There is a bug when using react-packages with MeteorJS and Semantic UI for infinite scroll. `onBottomVisible()` never fires.
- The bug occurs in Chrome (I'm using a MacBook) Version 44.0.2403.130 (64-bit).
- This works fine in Safari Version 7.1.7 (9537.85.16.12).

Also, this works fine in a ReactJS app in Chrome without Meteor, it's only when you use `react-packages` that this occurs. It also works with Meteor in Safari.

So far I've got it 1/2 working in Chrome (but only if do this):
1. Add this to index.html:
   `<meta name="viewport" content="initial-scale=1" />`
2. In Chrome Developer Tools turn on mobile device mode i.e. `Toggle device mode`.
3. Refresh the browser window, now scrolling down will fire `onBottomVisible()`.

I haven't figured out if there's a meta tag that will fix this when NOT in mobile browser emulation mode. i.e. on regular desktop.

**Comment by stubailo** [comment] 2015-09-29 00:54
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by giantelk** [comment] 2015-09-30 01:24
Here's the Reproduction repo:
https://github.com/giantelk/react-meteor-infinite-scroll-semantic-ui


On Mon, Sep 28, 2015 at 8:54 PM, Sashko Stubailo <notifications@github.com>
wrote:

> Please provide a full reproduction as described in:
> https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor
> Without a way to replicate your problem, we can't debug and fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/84#issuecomment-143913463>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by giantelk** [comment] 2015-09-30 03:15
Also see comments on this page:
https://github.com/Semantic-Org/Semantic-UI/issues/2815


On Tue, Sep 29, 2015 at 10:13 PM, Sashko Stubailo <notifications@github.com>
wrote:

> Reopened #84 <https://github.com/meteor/react-packages/issues/84>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/react-packages/issues/84#event-422606662>.
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by minfawang** [comment] 2015-10-15 05:04
I think I'm getting the same error here ...

**Comment by maitrid** [comment] 2016-11-02 22:56
I have the same problem. I'm using ES6 in Meteor-React, with Meteor version 1.4, using a div in a sub component which is inside other divs in the parent component. I'm using the Bootstrap framwork as well. onBottomVisible just won't fire, even after adding `offset: 5`.  It fires on page load though, which is not what i want. This example on jsfiddle works, bit it's on a top-level div: http://jsfiddle.net/q17w57ca/ .

**Comment by filipenevola** [comment] 2021-01-21 10:48
I'm closing this just because it's too old. We can open new issues for items that are still valid.

Most of these items were solved already or replaced by new strategies (like hooks)

**Closed by filipenevola** 2021-01-21 10:48 UTC
