### ISSUE TITLE
Multiple Reacts and "Only a ReactOwner can have refs" error

### ISSUE THREAD

**Issue by SachaG** [meteor/react-packages#168] opened 2016-01-20 00:48 UTC
I'm running into the following error with [my package](https://github.com/meteor-utilities/Meteor-Griddle/):

> Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

It seems it's because the full React code is being included in my package code, which means I end up with two copies of React loaded in memory. 

According to [this similar issue](https://github.com/meteor/react-packages/issues/11), it might have something to do with using Browserify inside my package?

**Comment by stubailo** [comment] 2016-01-20 00:55
I wonder if this has something to do with peer dependencies - I have only tested this approach with packages that depend on React directly.

So the way the Browserify transform is supposed to work is by replacing `require('react')` with `Package['react-runtime'].React.require('react')`, which prevents Browserify from following the dependency and actually bundling React. Do you have an example app or something so that I can look at the built output?

**Comment by SachaG** [comment] 2016-01-20 01:05
This will reproduce the bug: https://github.com/SachaG/react-bug-repro

It won't trigger the error but if you inspect the `utilities:meteor-griddle` code it contains React.

**Comment by SachaG** [comment] 2016-01-20 01:08
Oh actually I'm not sure… It does seem like it contains Underscore for some reason? I'm wondering if maybe the original Griddle package is to blame for some of this.

**Comment by SachaG** [comment] 2016-01-20 01:10
Maybe a better way to reproduce the bug is to run the actual app: https://github.com/DiscoverMeteor/BookApp/tree/react (private repo but I've given you access)

**Comment by ryanlanciaux** [comment] 2016-01-20 16:58
One of the Griddle authors here.. We are using underscore in this version (I wish we initially set it up to allow the user to choose underscore / lodash). In 1.0, it doesn't require either but pulls in just a couple of specific modules from lodash.

Please let me know if there's anything we're doing that's causing trouble for you and we'll see if we can get it resolved in the Griddle project. :+1: I'm not super familiar with the Meteor side of things but our goal is that it should work in anything really.

**Comment by ryanlanciaux** [comment] 2016-01-20 17:13
Additionally, is this using griddle from npm or from the full build?

**Comment by stubailo** [comment] 2016-01-20 17:16
This is from NPM, and it's reasonably likely the problem is on our end. I'll check it out soon!

**Comment by dagatsoin** [comment] 2016-01-20 21:29
Hi. I ran to this error after ```npm install material-ui``` in meteor 1.3.beta4
It seems that material ui imports reacts as well. Do you know how can I prrvent material ui to load react twice?

**Comment by tmeasday** [comment] 2016-01-22 06:00
@stubailo I had a look at this and I'm pretty sure it's just something in cosmos:browserify / externalify rather than anything to do with peer dependencies. 

I made a test app: https://github.com/tmeasday/test-griddle

If you run it and look at the compiled source for the griddle package, you'll see lines like 

```js
var React = require('react'); 
```

This should however have been transformed by externalify to this mess:

```js
var React = (typeof window !== "undefined" ? window['Package']['react-runtime']['React']['require'] : typeof global !== "undefined" ? global['Package']['react-runtime']['React']['require'] : null)("react");
```

I have no idea why it is not happening. The package *seems* to be configured identically to other packages I've written that similarly depend on and `require('react')`.

PS it's suspicious also that there's no `.browserify.js.cached` or `.browserify.js.map` file being created. I'm not sure if that's relevant but it's different to what I see in other packages.

**Comment by tmeasday** [comment] 2016-01-22 06:00
If I get a chance I'll poke further but I have to run now.

**Comment by oskareke** [comment] 2016-03-02 13:12
@SachaG Did you happen to find a solution for this issue?

**Comment by SachaG** [comment] 2016-03-04 14:20
The general solution I found was to not use `Npm.depends` in your package, and generally try to stick to importing packages via `npm install` whenever you can (i.e. no `Npm.depends`, no `meteorhacks:npm`, etc.).

**Comment by stubailo** [comment] 2016-03-04 19:05
Yes, in Meteor 1.3 the solution is to use NPM install. If you use NPM 3 you're basically guaranteed to have exactly one version of React in your app.

**Comment by tmeasday** [comment] 2016-03-08 06:33
Closing this

**Closed by tmeasday** 2016-03-08 06:33 UTC
