### ISSUE TITLE
Error: Cannot find module './lib/ReactPropTypesSecret'

### ISSUE THREAD

**Issue by maczyt** [meteor/react-packages#231] opened 2017-09-28 08:30 UTC
after `meteor add react-meteor-data`,
app throw an error: `.meteor/packages/meteor-tool/.1.5.2_1.1xez4yo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170928-16:24:01.269(8)? (STDERR)  throw(ex);
`

**Comment by abernix** [comment] 2017-09-28 16:47
Is that the whole error?  There is nothing to work with here unfortunately.  Can you please provide a complete reproduction on a small Meteor application?

**Comment by filipenevola** [comment] 2021-01-21 10:49
I'm closing this just because it's too old. We can open new issues for items that are still valid.

Most of these items were solved already or replaced by new strategies (like hooks)

**Closed by filipenevola** 2021-01-21 10:49 UTC
