### ISSUE TITLE
0.14.4 problem with Mup: 'no such file or directory, ... .../node_modules/esprima-fb/.#README.md'

### ISSUE THREAD

**Issue by Batistleman** [meteor/react-packages#165] opened 2016-01-14 13:03 UTC
There might be a problem with version 0.14.4

Related discussion here: https://forums.meteor.com/t/mupx-archiving-failed-enoent/15281
and here: https://github.com/arunoda/meteor-up/issues/812

**Comment by tmeasday** [comment] 2016-03-08 06:34
Any idea what the problem is?

**Comment by filipenevola** [comment] 2021-01-21 10:45
I'm closing this just because it's too old. We can open new issues for items that are still valid.

**Closed by filipenevola** 2021-01-21 10:45 UTC
