### ISSUE TITLE
Problems arise when using `meteor add react` with a browserified React package like material ui

### ISSUE THREAD

**Issue by grigio** [meteor/react-packages#11] opened 2015-06-09 13:46 UTC
I tried to `meteor add react` and add `material-ui` via `cosmos:browserify` but it seems the context is undefined.

No problem with react and material-ui added via `cosmos:browserify`

**Comment by pronevich** [comment] 2015-06-09 14:17
I have the same issue. Early I tried reactjs:react package with https://github.com/ukabu/material-ui but as a result I got the same issue as mentioned above.Then I have tried https://github.com/mrphu3074/react-material-ui/ and it's works fine, this package exports all components globally.

Now with react-packages I do it right and add material-ui via npm and cosmos:browserify but I can't use components because context is undefined.

**Comment by stubailo** [comment] 2015-06-09 16:38
The problem involves those packages pulling in their own browserified
React; we end up with two reacts, and they can't share the context. I'm
thinking about ways to fix this.

**Comment by grigio** [comment] 2015-06-09 16:57
@stubailo I've seen you removed `cosmos:browserify` as dependency and bundled ReactRouter in lib/ what is the alternative to install browserified dependencies like ReactRouter, material-ui,.. ?

Could and approch be to install the browserified dependencies via `Npm.depends({..})` or an ad-hoc package support ?
```
Browserify.depends({
  'react-router':'0.13.3',
  'material-ui':'0.8.0'
});
```

**Comment by stubailo** [comment] 2015-06-09 17:49
@grigio no, that doesn't help. The problem is that as soon as you install a package that depends on `react`, you get a second copy of React.

We're going to implement proper NPM/Browserify support soon, but probably not in the next few weeks.

**Comment by grigio** [comment] 2015-06-09 18:49
I mean Material UI works if you install React via cosmos:browserify and the rest a la Meteor way.
You removed cosmos:browserify as dep, is there something wrong with it?

**Comment by stubailo** [comment] 2015-06-09 19:03
Ah, you're saying you could use the `react` npm package rather than `meteor add react`. That should probably work. Does that end up loading the right version of React for production/development?

Also, if you load React over NPM, then the `MeteorDataMixin` still works, right?

There's nothing particularly wrong with `cosmos:browserify`, but I wasn't happy with the lack of configuration, for example. I decided to defer worrying about that until later.

**Comment by grigio** [comment] 2015-06-10 08:14
Yes, you can't choose the React production/development but the rest works pretty well. I wrote a [post](http://grigio.org/meteor-react-and-material-ui-the-easy-way/) about it.

**Comment by stubailo** [comment] 2015-06-22 01:01
@grigio try this: https://github.com/meteor/react-packages/blob/master/docs/client-npm.md

The new version of cosmos:browserify supports transforms, so you can use exposify to use the Meteor React package.

**Comment by grigio** [comment] 2015-06-22 09:02
I tried a few alternative integrations, but I'm not sure I can use `meteor-react`instead of `npm-react` to run `npm-material-ui` at package level.

Or maybe you mean to load meteor-react, exposify `React`and then load `npm-material-ui` all the meteor app without private packages?

```
=> Started proxy.                             
=> Started MongoDB.                           
W20150622-10:16:52.122(2)? (STDERR)           
W20150622-10:16:52.124(2)? (STDERR) /Users/grigio/.meteor/packages/meteor-tool/.1.1.3.ttennc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150622-10:16:52.125(2)? (STDERR) 						throw(ex);
W20150622-10:16:52.125(2)? (STDERR) 						      ^
W20150622-10:16:52.350(2)? (STDERR) TypeError: Cannot read property 'PropTypes' of undefined
W20150622-10:16:52.351(2)? (STDERR)     at Object.<anonymous> (lib/node_modules/material-ui/lib/ripples/focus-ripple.js:17:1)
W20150622-10:16:52.351(2)? (STDERR)     at Object.../mixins/style-propable (lib/node_modules/material-ui/lib/ripples/focus-ripple.js:92:1)
```
```
=> Modified -- restarting.                    
browserify-deps: updating npm dependencies -- react, material-ui...
                                              
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'exposify' from '/Users/grigio/+persistant/Code/testing/react-materialui-demo/packages/browserify-deps/.npm/package'
    at /Users/grigio/.meteor/packages/cosmos_browserify/.0.4.0.1v8md0x++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/grigio/.meteor/packages/cosmos_browserify/.0.4.0.1v8md0x++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
```

**Comment by grigio** [comment] 2015-06-22 09:53
@stubailo I tried to integrate Material UI at app-level

`meteor add React`

it loaded and present before:
```
// lib/app.browserify.js
mui = require("material-ui");
```
```
// lib/app.browserify.options.json
{
  "transforms": {
    "exposify": {
      "global": true,
      "expose": {
        "react": "React"
      }
    }
  }
}
```
```
// packages.json
{
  "exposify": "0.4.3",
  "material-ui": "0.8.0"
}
```
the UI is loaded but it is unusable, it seems `React` has been loaded twice
```
// inside inspector
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.
```

**Comment by stubailo** [comment] 2015-06-22 17:48
I have created a minimal material UI example here: https://github.com/meteor/react-packages/tree/master/material-ui-example

Can you help me construct one that fails in the way you describe?

**Comment by grigio** [comment] 2015-06-22 19:32
@stubailo Your example seems to work, but if I replace
```
var RaisedButton = mui.RaisedButton;
```
with
```
var DatePicker = mui.DatePicker;
```
and
```
<RaisedButton label="Default" />
```
with:
```
<DatePicker />
```
It doesn't work anymore:
> Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

To get the previous error you can replace on your example `material-ui-example.jsx` with [this](https://github.com/grigio/meteor-react-material-ui-demo/blob/master/client/Main.jsx) and you reproduce the error.

**Comment by stubailo** [comment] 2015-06-22 20:43
Thanks for the repro! I'll look into it.

**Comment by stubailo** [comment] 2015-06-22 22:59
@grigio confirmed, my transform doesn't work in this case because material-ui uses `require("react/addons")` everywhere instead of `require("react")`.

**Comment by stubailo** [comment] 2015-06-23 21:30
This was the result of this issue: https://github.com/thlorenz/exposify/issues/15

As soon as `exposify` is updated, I'll update the guide and Material UI should work.

**Comment by grigio** [comment] 2015-06-23 21:53
Nice, how did you find/debugged that? the errors seems doesn't seem related

**Comment by stubailo** [comment] 2015-06-23 21:54
The problem is that material-ui uses `require("react/addons")` all over the place instead of `require("react")`.

**Comment by stubailo** [comment] 2015-06-24 23:31
@grigio this should work now - check the example: https://github.com/meteor/react-packages/tree/master/examples/material-ui-example

You just need to delete your `.npm` folder and re-build dependencies, so that you get `replace-requires@1.0.3`: https://github.com/meteor/react-packages/blob/882c86e4ab2119bd23e22e08d4697ab18ed6d97c/examples/material-ui-example/packages/npm-container/.npm/package/npm-shrinkwrap.json#L21

**Comment by pronevich** [comment] 2015-06-25 18:43
I have tested this example. The UI is rendered and there are no errors, but actions (clicks) don't work. For example, I can't open DatePicker dialog and etc.

**Comment by stubailo** [comment] 2015-06-25 19:01
I guess I don't really know how it's supposed to work - I thought maybe I was using it wrong or something.

**Comment by stubailo** [comment] 2015-06-25 19:13
Weird - I just ran the example, and the date picker is actually rendered to the DOM - it just doesn't show up. So I don't think it's actually a problem with Browserify, it's something else.

**Comment by pronevich** [comment] 2015-06-25 19:24
There is nothing wrong with example code. I tested it also in another react + meteor solution by grigio and everything works fine.

**Comment by stubailo** [comment] 2015-06-25 20:16
@pronevich can you link to that code please? I want to see what it does.

**Comment by stubailo** [comment] 2015-06-25 20:21
It seems to be an issue with the touchTap event: https://github.com/callemall/material-ui/blob/1790591cc2051b7c6c458cf7afc3271007b21c5c/src/date-picker/date-picker.jsx#L131 (that's the event that actually opens the dialog)

I think to enable it you need the touch tap plugin: https://github.com/zilverline/react-tap-event-plugin

I've tried installing that plugin, and it doesn't work yet - I might be doing something wrong.

**Comment by stubailo** [comment] 2015-06-25 20:22
Ok, that's the issue - that plugin doesn't work. Going to look into this.

**Comment by grigio** [comment] 2015-06-26 08:19
I think it's a problem in meteor/browserify, I tried to load `injectTapEventPlugin = require("react-tap-event-plugin");` as it should but it an empty function

**Comment by stubailo** [comment] 2015-06-26 17:24
Yeah, I know what the issue is, fixing it today.

**Comment by stubailo** [comment] 2015-06-26 22:16
OK, I have now definitively solved this issue with a brand new Browserify transform called `externalify`. See how to use it here: http://react-in-meteor.readthedocs.org/en/latest/client-npm/#4-configure-browserify-and-transforms-in-appbrowserifyoptionsjson

**Comment by grigio** [comment] 2015-06-26 22:19
I confirm just tried #22 , thanks @stubailo

**Comment by KristerV** [comment] 2015-07-17 11:57
I still get the same error mentioned way up there.

    Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

I am currently using externalify, just like @stubailo's last link suggests (and how the react-package examples suggest). The only difference is that I'm trying to make a package out of MUI.

The current state of my plugin is [here](https://github.com/KristerV/meteor-material-ui). The "package" dir is for package itself and "demo" is a small demo app to test the package (run meteor).

**Comment by lourd** [comment] 2015-07-17 17:46
https://github.com/meteor/react-packages/issues/61discusses this is as well

**Comment by stubailo** [comment] 2015-07-17 18:17
Reopened primarily because there is a suspicion it doesn't work inside packages. I'll try it out later and report back.

**Comment by KristerV** [comment] 2015-07-18 08:06
okay.. uhmm.. thanks to [mrphu3074 and his package](https://github.com/mrphu3074/react-material-ui/issues/2) I managed to get it working by simply adding react as a dependency to the package. I do not know why the "owner, parent context" error does not appear anymore, this makes no sense bu it works..

I've also updated my package so you can have a try if you like. But it seems that we have a [material-ui package now](https://github.com/mrphu3074/react-material-ui) so this issue can be closed as far as I'm concerned.

**Comment by stubailo** [comment] 2015-07-18 17:40
OK, will close again; if it comes up again we can revisit it. Eventually we will have support for NPM packages without `cosmos:browserify`, and then we can solve this issue once and for all.

**Comment by KristerV** [comment] 2015-07-18 19:05
you forgot to close. Could you link us to whatever this NPM fix is going to be? so I can keep an eye out.

**Comment by stubailo** [comment] 2015-07-18 19:17
Sorry, there isn't anywhere to link to yet!

**Closed by stubailo** 2015-07-18 19:17 UTC

**Comment by vdavid** [comment] 2015-12-03 13:44
For me (and Meteor 1.2.1), the above solution did not work. For material-ui, this Meteor package helped me, it works flawlessly: https://atmospherejs.com/markoshust/material-ui

**Comment by SylarRuby** [comment] 2015-12-31 05:27
I almost went back to Rails. Thank you @stubailo for: https://github.com/meteor/react-packages/blob/master/docs/client-npm.md

**Comment by SachaG** [comment] 2016-01-20 00:42
I'm running into the same issue… I must be doing something wrong with the way I set up my dependencies? Here's the repo: https://github.com/meteor-utilities/Meteor-Griddle

**Comment by stubailo** [comment] 2016-01-20 00:45
@SachaG can you post a separate issue? This one is a bit long and about material UI.
