### ISSUE TITLE
componentWillMount is called before subscription is ready when using createContainer

### ISSUE THREAD

**Issue by javoire** [meteor/react-packages#186] opened 2016-04-17 13:54 UTC
I've scoured the web for hours now and read the source for `react-meteor-data` and I can't figure out what's wrong. So my understanding is that `createContainer` will create a wrapper container component that'll reactively get data from a meteor subscription, and then pass it down to the actual component, `AuthContainer` in this case.

However, `componentWillMount` is called before the subscription is ready and thus the user will always be redirected to `/login` (see example below).

I've been following all examples out there that I could find of how to set this up.

How do I configure the meteor data container to **not** do anything until the subscription is ready?

Example:

``` js
import React, { Component, PropTypes } from 'react';
import { createContainer } from 'meteor/react-meteor-data';
import { browserHistory } from 'react-router';

import AppContainer from '/imports/ui/containers/AppContainer.jsx';

class AuthContainer extends Component {

  constructor(props) {
    super(props);

    this.checkAuth = this.checkAuth.bind(this);
  }

  checkAuth() {
    // (2) so this returns false, thus always redirecting to login page
    if (!this.props.currentUser) {
      browserHistory.replace('/login')
    }
  }

  componentWillMount() {
    // (1) this is called instantly
    this.checkAuth();
  }

  componentDidUpdate() {
    this.checkAuth();
  }

  render() {
    return (
      <AppContainer currentUser={this.props.currentUser} />
    )
  }
}

AuthContainer.propTypes = {
  currentUser: PropTypes.object,
};

// (3) I'd like this to not instantiate the AuthContainer until subscriptions are ready
export default createContainer(() => {
  Meteor.subscribe("user");
  return {
    currentUser: Meteor.user()
  }
}, AuthContainer);
```

**Comment by javoire** [comment] 2016-04-17 14:28
Solution: do auth check in `componentDidMount`. Still don't understand why this code should work though: https://alexgaribay.com/2015/10/13/authenticated-routes-with-meteor-and-react-router/, which is what based mine on!

**Comment by javoire** [comment] 2016-04-17 14:33
Actually I'd like to keep this open for a bit more. In his example, it looks like `componentWillMount` is _not_ executed until the subscription is ready, which is not the case in my code.

**Comment by javoire** [comment] 2016-04-17 15:41
I'm suspecting that I'm just getting race lucky using `componentDidMount`, in the way that most of the times the subscription happens to be ready before `componentDidMount` is called. Because sometimes I get the previous behaviour of redirect to `/login` even though there is a logged in user.

**Comment by ericfortis** [comment] 2016-04-20 06:24
Using the `ready()` property of subscription handle.

```javascript
class AuthContainer extends Component {
  constructor(props) {
    super(props);
    this.checkAuth = this.checkAuth.bind(this);
  }

  componentDidMount() {
    this.checkAuth(this.props);
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.userLoaded !== this.props.userLoaded) {
      this.checkAuth(nextProps);
    }
  }

  checkAuth(props) {
    if (props.userLoaded && !props.currentUser) {
      browserHistory.replace('/login');
    }
  }

  render() {
    if (this.props.userLoaded && this.props.currentUser) {
      return (
        <AppContainer currentUser={this.props.currentUser}/>
      );
    }
    return null; // <LoadingSpinner/>
  }

}

AuthContainer.propTypes = {
  currentUser: PropTypes.object,
  userLoaded:  PropTypes.bool
};

export default createContainer(() => {
  const userSubscription = Meteor.subscribe("user");
  return {
    currentUser: Meteor.user(),
    userLoaded:  userSubscription.ready()
  }
}, AuthContainer);
```

**Comment by javoire** [comment] 2016-04-20 22:11
Thanks, looking at that it totally makes sense to listen for received props rather than mounting. However, regardless of how I twist and turn this code, the subscription handlers ready() function is not behaving as expected. 

```js
class AppContainer extends Component {
  componentWillReceiveProps(nextProps) {
    debugger // never reached
  }
  componentDidUpdate() {
    debugger // never reached
  }
  componentWillUpdate() {
    debugger // never reached
  }
  componentDidMount() {
    debugger // ... third
  }
  componentWillMount() {
    debugger // reached first...
  }
  render() {
    if (this.props.userLoaded) { // this is always false
      debugger // not reached due to conditional false above
      return (
        <MainContainer children={this.props.children} />
      )
    }

    debugger // ... second
    return <div>Loader...</div>
  }
}

AppContainer.propTypes = {
  currentUser: PropTypes.object,
  userLoaded: PropTypes.object,
}

export default createContainer(() => {
  const userSubscription = Meteor.subscribe('user');
  return {
    currentUser: Meteor.user(),
    userLoaded: userSubscription.ready()
  }
}, AppContainer);
```

Your example code looks perfectly fine, just like all other examples out there using `.ready()`. But I don't get the correct behaviour. 

You can see the order of the breakpoints that are reached and the ones that are never reached in the code above. 

Not sure what I'm missing. I'd like to try this in more isolation. This component is also wrapped in react-router. But other than that, it's a very minimal setup.

**Comment by ericfortis** [comment] 2016-04-20 23:22
Since you changed `userLoaded` from bool to object, I'd say that the issue is in the publication of the custom `'user`.

**Comment by javoire** [comment] 2016-04-21 15:20
damn it it's an error in the example, it is a `PropTypes.bool` all the tweaking made me copy paste example code. The example is now updated.

Though your point about the publication of the user is good, guess I need to call the `handler.ready()` function manually in the publication. Allthough I would expect meteor to do that for me. My publication is returning the handler of `Meteor.users.find()`.

```js
// null apparently works for the built in Meteor.user() collection
Meteor.publish(null, function userPublication() {
  return Meteor.users.find({ _id: this.userId }, { fields: { 'newUser': 1 }});
});
```

**Comment by javoire** [comment] 2016-04-21 18:44
So, today, 24 hours later, I try again. On the 3 first refreshes of the page, I get all breakpoints to be reached. Then all subsequent refreshes only the ones in the example above.

I've also removed the custom user publication, I've also removed the react-router. This behaviour seems completely inconsistent and indeterministic. I have no clue what I'm missing. 

My understanding is that `componentWillReceiveProps` will get called, since the wrapping `MeteorDataContainer` will set that subscribed data as props on this component. I'm out of ideas at the moment.

**Comment by javoire** [comment] 2016-04-21 18:50
So maybe the subscription is fast enough to be done before `AppContainer` mounts? https://facebook.github.io/react/tips/componentWillReceiveProps-not-triggered-after-mounting.html

however `userLoaded: userSubscription.ready()` is _always_ false even though `currentUser: Meteor.user(),` has the user object

**Comment by filipenevola** [comment] 2021-01-21 10:45
I'm closing this just because it's too old. We can open new issues for items that are still valid.

**Closed by filipenevola** 2021-01-21 10:45 UTC
