### ISSUE TITLE
React 16.3 => migration from componentWillMount and componentWillUpdate

### ISSUE THREAD

**Issue by fabien-h** [meteor/react-packages#252] opened 2018-03-30 14:01 UTC
Not blocking at the moment ; but we have some ugly warning :)

**Comment by softwarecreations** [comment] 2019-08-12 16:51
Reproduce deprecation warnings with 3 commands:
```
curl https://install.meteor.com/ | sh
cd /tmp; meteor create --react foo
cd foo; meteor
```
Warnings produced by react 16 in the automatically generated `package.json`
```
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
```
![image](https://user-images.githubusercontent.com/28704571/62879109-b1285f80-bd2a-11e9-9cd2-075adf48b875.png)

Finding offending code:
```
grep -rn ~/.meteor -e "componentWill\(Mount\|Update\)"

~/.meteor/packages/react-meteor-data/.0.2.16.w4vu92.v54d++os+web.browser+web.cordova/os/ReactMeteorData.jsx:127:  componentWillMount() {
~/.meteor/packages/react-meteor-data/.0.2.16.w4vu92.v54d++os+web.browser+web.cordova/os/ReactMeteorData.jsx:134:  componentWillUpdate(nextProps, nextState) {
```

https://github.com/meteor/react-packages/blob/b55f96d0c668bc8379f913011a85647e2907667b/packages/react-meteor-data/ReactMeteorData.jsx#L127

**Comment by Twisterking** [comment] 2019-08-22 10:08
Will there be any updates on this? Or do I have to fork it and rename it to `UNSAFE_...` myself?

**Comment by dburles** [comment] 2019-08-22 11:21
https://github.com/meteor/react-packages/pull/273

**Comment by filipenevola** [comment] 2019-11-19 12:11
closing because of react-meteor-data@2.0.0 https://github.com/meteor/react-packages/pull/273

**Closed by filipenevola** 2019-11-19 12:11 UTC
